#Script with functions that create datacards

def create_datacard(root_file_name,data_int,mu_int,tau_int,x_int,dat_name='datacard'):


    f= open("datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 2 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes * * /work/friti/new/CMSSW_10_2_15/src/pyrk/root_files/%s $PROCESS \n"%root_file_name) 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin rjpsi\n") 
    f.write("observation %s\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t rjpsi \t rjpsi \t rjpsi\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id\n") 
    f.write("process \t 1 \t 0 \t 2\n") 
    f.write("rate \t %s \t %s \t %s \n"%(mu_int,tau_int,x_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam rjpsi mc_mu 1\n") 
    f.write("mis_id_unc lnN - - 1.5\n") 
    f.write("#rjpsi autoMCStats 1\n") 
    f.close()

#create_datacard("Bm_miss_sq2.root",16626,14863.04568741178,1040.9416810714274,721.9011999999963)
def create_datacard_5(root_file_name,data_int,mu_int,tau_int,mis_int,comb_int,dat_name='datacard'):

    f= open("datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes * * /work/friti/new/CMSSW_10_2_15/src/pyrk/scripts/root_files/%s $PROCESS \n"%root_file_name) 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin rjpsi\n") 
    f.write("observation %s\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t rjpsi \t rjpsi \t rjpsi \t rjpsi\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %s \t %s \t %s \t %s \n"%(mu_int,tau_int,mis_int,comb_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam rjpsi mc_mu 1\n") 
    f.write("mis_id_unc lnN - - 1.5 - \n") 
    f.write("mc_comb_unc lnN - - - 1.5 \n") 
    f.write("#rjpsi autoMCStats 1\n") 
    f.close()

def create_datacard_signal(data_int,mu_int,tau_int,mis_int,comb_int,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    signal   param_ws.root wspace:data_obs_SR \n")
    f.write("shapes mis_id      signal   param_ws.root wspace:misid_SR \n")
    f.write("shapes mc_mu       signal   param_ws.root wspace:mu_SR \n")
    f.write("shapes mc_tau      signal   param_ws.root wspace:tau_SR \n")
    f.write("shapes mc_comb      signal   param_ws.root wspace:comb_SR \n")

    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin signal\n") 
    f.write("observation %.2f\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t signal \t signal \t signal \t signal\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \n"%(mu_int,tau_int,1,comb_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam signal mc_mu 1\n") 
    f.write("mu_norm rateParam signal mc_tau 1\n") 
    f.write("mis_id_unc lnN - - 1.2 - \n") 
    f.write("recoMuon lnN 1.10 1.10 - 1.10 \n") 
    f.write("mc_comb_unc lnN - - - 1.5 \n") 
    f.write("#signal autoMCStats 1\n") 
    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")

def create_datacard_control(data_int,mu_int,tau_int,mis_int,comb_int,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    control   param_ws.root wspace:data_obs_CR \n")
    f.write("shapes mis_id      control   param_ws.root wspace:misid_CR \n")
    f.write("shapes mc_mu       control   param_ws.root wspace:mu_CR \n")
    f.write("shapes mc_tau      control   param_ws.root wspace:tau_CR \n")
    f.write("shapes mc_comb      control   param_ws.root wspace:comb_CR \n")

    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin control\n") 
    f.write("observation %.2f\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t control \t control \t control \t control\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \n"%(mu_int,tau_int,1,comb_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam control mc_mu 1\n") 
    f.write("mu_norm rateParam control mc_tau 1\n") 
    f.write("mis_id_unc lnN - - 1.2 - \n") 
    f.write("recoMuon lnN 0.9 0.9 - 0.9 \n") 
    f.write("mc_comb_unc lnN - - - 1.5 \n") 
    f.write("-----------------------------------------------\n") 
    f.write("misid_CR_bin1  flatParam \n")
    f.write("misid_CR_bin2  flatParam \n")
    f.write("misid_CR_bin3  flatParam \n")
    f.write("misid_CR_bin4  flatParam \n")
    f.write("misid_CR_bin5  flatParam \n")
    f.write("misid_CR_bin6  flatParam \n")
    f.write("misid_CR_bin7  flatParam \n")
    f.write("misid_CR_bin8  flatParam \n")
    f.write("misid_CR_bin9  flatParam \n")    
    f.write("misid_CR_bin10  flatParam \n")
    f.write("misid_CR_bin11  flatParam \n")
    f.write("misid_CR_bin12  flatParam \n")
    f.write("misid_CR_bin13  flatParam \n")
    f.write("misid_CR_bin14  flatParam \n")
    f.write("misid_CR_bin15  flatParam \n")

    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")


def create_datacard_pf(root_file_name_fail, root_file_name_pass, data_int,mu_int,tau_int,comb_int,mis_int,data_int1,mu_int1,tau_int1,comb_int1,mis_int1,dat_name='datacard'):


    f= open("datacard_" + dat_name + ".txt","w")
    f.write("imax 2 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes * tight0 /work/friti/new/CMSSW_10_2_15/src/pyrk/scripts/root_files/%s $PROCESS \n"%root_file_name_fail) 
    f.write("shapes * tight1 /work/friti/new/CMSSW_10_2_15/src/pyrk/scripts/root_files/%s $PROCESS \n"%root_file_name_pass) 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin \t tight0 \t tight1\n") 
    f.write("observation \t %s \t %s\n"%(data_int,data_int1)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t tight0 \t tight0 \t tight0 \t tight0 \t tight1 \t tight1 \t tight1 \t tight1 \n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3 \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \n"%(mu_int,tau_int,mis_int,comb_int,mu_int1,tau_int1,mis_int1,comb_int1)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu0 rateParam tight0 mc_mu 1\n") 
    f.write("mu0 rateParam tight1 mc_mu 1 \n") 
    f.write("misid_unc  lnN - - 1.5 - - - 1.5 - \n")
    f.write("comb_unc lnN - - - 1.5 - - - 1.5 \n")
    f.write("#misid0 rateParam tight0 mis_id 1 \n") 
    f.write("#misid0 rateParam tight1 mis_id 1\n") 
    f.write("#comb0 rateParam tight0 mc_comb 1\n") 
    f.write("#comb0 rateParam tight1 mc_comb 1\n") 
    f.close()
    print("Saved datacard ' datacard_"+ dat_name+".txt'")
