def create_datacard_signal(data_int,mu_int,tau_int,mis_int,comb_int,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    signal   param_ws.root wspace:data_obs_SR \n")
    f.write("shapes mis_id      signal   param_ws.root wspace:misid_SR \n")
    f.write("shapes mc_mu       signal   param_ws.root wspace:mu_SR \n")
    f.write("shapes mc_tau      signal   param_ws.root wspace:tau_SR \n")
    f.write("shapes mc_comb      signal   param_ws.root wspace:comb_SR \n")

    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin signal\n") 
    f.write("observation %.2f\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t signal \t signal \t signal \t signal\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \n"%(mu_int,tau_int,1,comb_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam signal mc_mu 1\n") 
    f.write("mu_norm rateParam signal mc_tau 1\n") 
    f.write("mis_id_unc lnN - - 1.2 - \n") 
    f.write("recoMuon lnN 1.10 1.10 - 1.10 \n") 
    f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    f.write("#signal autoMCStats 1\n") 
    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")

def create_datacard_control(data_int,mu_int,tau_int,mis_int,comb_int,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax 3 number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    control   param_ws.root wspace:data_obs_CR \n")
    f.write("shapes mis_id      control   param_ws.root wspace:misid_CR \n")
    f.write("shapes mc_mu       control   param_ws.root wspace:mu_CR \n")
    f.write("shapes mc_tau      control   param_ws.root wspace:tau_CR \n")
    f.write("shapes mc_comb      control   param_ws.root wspace:comb_CR \n")

    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin control\n") 
    f.write("observation %.2f\n"%data_int) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t control \t control \t control \t control\n") 
    f.write("process \t mc_mu \t mc_tau \t mis_id \t mc_comb\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3\n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \n"%(mu_int,tau_int,1,comb_int)) 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam control mc_mu 1\n") 
    f.write("mu_norm rateParam control mc_tau 1\n") 
    f.write("mis_id_unc lnN - - 1.2 - \n") 
    f.write("recoMuon lnN 0.9 0.9 - 0.9 \n") 
    f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    f.write("-----------------------------------------------\n") 
    f.write("misid_CR_bin1  flatParam \n")
    f.write("misid_CR_bin2  flatParam \n")
    f.write("misid_CR_bin3  flatParam \n")
    f.write("misid_CR_bin4  flatParam \n")
    f.write("misid_CR_bin5  flatParam \n")
    f.write("misid_CR_bin6  flatParam \n")
    f.write("misid_CR_bin7  flatParam \n")
    f.write("misid_CR_bin8  flatParam \n")
    f.write("misid_CR_bin9  flatParam \n")    
    f.write("misid_CR_bin10  flatParam \n")
    f.write("misid_CR_bin11  flatParam \n")
    f.write("misid_CR_bin12  flatParam \n")
    f.write("misid_CR_bin13  flatParam \n")
    f.write("misid_CR_bin14  flatParam \n")
    f.write("misid_CR_bin15  flatParam \n")

    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")

