def create_datacard_signal(data_int,his,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax * number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    signal   param_ws.root wspace:data_obs_SR \n")
    f.write("shapes mu       signal   param_ws.root wspace:mc_mu_SR #wspace:mc_mu_ctauUp_SR wspace:mc_mu_ctauDown_SR \n")
    f.write("shapes tau      signal   param_ws.root wspace:mc_tau_SR #wspace:mc_tau_ctauUp_SR wspace:mc_tau_ctauDown_SR \n")
    f.write("shapes chic0      signal   param_ws.root wspace:chic0_SR \n")
    f.write("shapes chic1      signal   param_ws.root wspace:chic1_SR \n")
    f.write("shapes chic2      signal   param_ws.root wspace:chic2_SR \n")
    f.write("shapes hc_mu      signal   param_ws.root wspace:hc_mu_SR \n")
    f.write("shapes jpsi_hc      signal   param_ws.root wspace:jpsi_hc_SR \n")
    f.write("shapes psi2s_mu      signal   param_ws.root wspace:psi2s_mu_SR \n")
    f.write("shapes psi2s_tau      signal   param_ws.root wspace:psi2s_tau_SR \n")
    f.write("shapes comb      signal   param_ws.root wspace:mc_comb_SR \n")
    f.write("shapes mis_id      signal   param_ws.root wspace:mis_id_SR \n")
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin signal\n") 
    f.write("observation %.2f\n"%data_int)
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t signal \t signal \t signal \t signal \t signal \t signal \t signal \t signal \t signal \t signal \t signal \n") 
    f.write("process \t mu \t tau \t chic0 \t chic1 \t chic2 \t hc_mu \t jpsi_hc \t psi2s_mu \t psi2s_tau \t comb \t mis_id\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3 \t 4 \t 5 \t 6 \t 7 \t 8 \t 9 \t 10 \n") 
    f.write("rate  \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f\n"%(his[0].Integral(),his[1].Integral(),his[2].Integral(),his[3].Integral(),his[4].Integral(),his[5].Integral(),his[6].Integral(),his[7].Integral(),his[8].Integral(),his[9].Integral()))
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam signal mu 1\n") 
    f.write("mu_norm rateParam signal tau 1\n") 
    f.write("mu_norm rateParam signal chic0 1\n")
    f.write("mu_norm rateParam signal chic1 1\n") 
    f.write("mu_norm rateParam signal chic2 1\n")
    f.write("mu_norm rateParam signal hc_mu 1\n")
    f.write("mu_norm rateParam signal jpsi_hc 1\n")
    f.write("mu_norm rateParam signal psi2s_mu 1\n")
    f.write("mu_norm rateParam signal psi2s_tau 1\n")
    f.write("comb_norm rateParam signal comb 1\n")
    f.write("#mis_id_unc lnN - - 1.2 - \n") 
    f.write("#recoMuon lnN 1.10 1.10 - 1.10 \n") 
    f.write("#ctau shape 1 1 - - - - - - - - - \n") 
    f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    f.write("#signal autoMCStats 1\n") 
    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")

def create_datacard_control(data_int,his,dat_name='datacard'):

    f= open("datacards/datacard_" + dat_name + ".txt","w")
    f.write("imax 1 number of channels \n")
    f.write("jmax * number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes data_obs    control   param_ws.root wspace:data_obs_CR \n")
    f.write("shapes mu       control   param_ws.root wspace:mc_mu_CR #wspace:mc_mu_ctauUp_CR wspace:mc_mu_ctauDown_CR \n")
    f.write("shapes tau      control   param_ws.root wspace:mc_tau_CR #wspace:mc_tau_ctauUp_CR wspace:mc_tau_ctauDown_CR \n")
    f.write("shapes chic0      control   param_ws.root wspace:chic0_CR \n")
    f.write("shapes chic1      control   param_ws.root wspace:chic1_CR \n")
    f.write("shapes chic2      control   param_ws.root wspace:chic2_CR \n")
    f.write("shapes hc_mu      control   param_ws.root wspace:hc_mu_CR \n")
    f.write("shapes jpsi_hc      control   param_ws.root wspace:jpsi_hc_CR \n")
    f.write("shapes psi2s_mu      control   param_ws.root wspace:psi2s_mu_CR \n")
    f.write("shapes psi2s_tau      control   param_ws.root wspace:psi2s_tau_CR \n")
    f.write("shapes comb      control   param_ws.root wspace:mc_comb_CR \n")
    f.write("shapes mis_id      control   param_ws.root wspace:mis_id_CR \n")
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin control\n") 
    f.write("observation %.2f\n"%data_int)
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin \t control \t control \t control \t control \t control \t control \t control \t control \t control \t control \t control \n") 
    f.write("process \t mu \t tau \t chic0 \t chic1 \t chic2 \t hc_mu \t jpsi_hc \t psi2s_mu \t psi2s_tau \t comb \t mis_id\n") 
    f.write("process \t 1 \t 0 \t 2 \t 3 \t 4 \t 5 \t 6 \t 7 \t 8 \t 9 \t 10 \n") 
    f.write("rate \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f \t %.2f  \t %.2f\n"%(his[0].Integral(),his[1].Integral(),his[2].Integral(),his[3].Integral(),his[4].Integral(),his[5].Integral(),his[6].Integral(),his[7].Integral(),his[8].Integral(),his[9].Integral()))
    f.write("----------------------------------------------------------------------------\n") 
    f.write("mu_norm rateParam control mu 1\n") 
    f.write("mu_norm rateParam control tau 1\n") 
    f.write("mu_norm rateParam control chic0 1\n")
    f.write("mu_norm rateParam control chic1 1\n") 
    f.write("mu_norm rateParam control chic2 1\n")
    f.write("mu_norm rateParam control hc_mu 1\n")
    f.write("mu_norm rateParam control jpsi_hc 1\n")
    f.write("mu_norm rateParam control psi2s_mu 1\n")
    f.write("mu_norm rateParam control psi2s_tau 1\n")
    f.write("#mis_id_unc lnN - - 1.2 - \n") 
    f.write("#recoMuon lnN 0.9 0.9 - 0.9 \n") 
    f.write("#ctau shape 1 1 - - - - - - - - - - \n") 
    f.write("comb_norm rateParam control comb 1\n")
    f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    f.write("-----------------------------------------------\n") 
    f.write("misid_CR_bin1  flatParam \n")
    f.write("misid_CR_bin2  flatParam \n")
    f.write("misid_CR_bin3  flatParam \n")
    f.write("misid_CR_bin4  flatParam \n")
    f.write("misid_CR_bin5  flatParam \n")
    f.write("misid_CR_bin6  flatParam \n")
    f.write("misid_CR_bin7  flatParam \n")
    f.write("misid_CR_bin8  flatParam \n")
    f.write("misid_CR_bin9  flatParam \n")    
    f.write("misid_CR_bin10  flatParam \n")
    f.write("misid_CR_bin11  flatParam \n")
    f.write("misid_CR_bin12  flatParam \n")
    f.write("misid_CR_bin13  flatParam \n")
    f.write("misid_CR_bin14  flatParam \n")
    f.write("misid_CR_bin15  flatParam \n")

    f.close()
    print("Saved datacard 'datacards/datacard_" + dat_name + ".txt'")

